# Generated by Django 3.2.25 on 2026-03-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Department Title')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Employee Name')),
                ('password', models.CharField(max_length=20, verbose_name='Employee Password')),
                ('age', models.IntegerField(verbose_name='Employee Age')),
                ('account_number', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Employee Account Number')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Employee Create Time')),
                ('gender', models.SmallIntegerField(choices=[('1', '男'), ('2', '女')], verbose_name='Employee Gender')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='Department')),
            ],
        ),
    ]
