# Generated by Django 3.2.25 on 2026-03-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='account_number',
            new_name='account',
        ),
    ]
