# Generated by Django 3.2.25 on 2026-03-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_account_number_employee_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_time',
            field=models.DateTimeField(verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
    ]
